version: '3.8'

services:
  app:
    image: debian:10
    container_name: debian_app
    ports:
      - "8080:80"      # Expose Nginx on port 8080
      - "2222:22"      # Expose SSH on port 2222
    volumes:
      - ./installation_files/:/home/appuser/installation_files/
    environment:
      - PATH="/root/venv/bin:$PATH"  # Set PATH to include virtual environment
    command: |
      bash -c "
        # Update package index and install Python 3
        apt-get update && \
        apt-get install -y python3 python3-pip && \
        
        # Verify Python installation
        python3 --version && \
        pip3 --version
      "