---
- name: Set up frontend and backend services
  hosts: localhost
  become: true
  tasks:
    - name: Update apt and install required packages
      apt:
        update_cache: yes
        name: 
          - nginx
          - python3
          - python3-pip
        state: present

    - name: Install Flask with pip
      pip:
        name: Flask

    - name: Copy frontend index.html to nginx web root
      copy:
        src: /root/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configure nginx to serve index.html
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: 'root /var/www/html;'
        line: 'root /var/www/html;'
        backup: yes
      notify: restart nginx

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Start backend service
      command: python3 /root/app.py &
