---
- name: Set up frontend and backend services on Alpine
  hosts: localhost
  become: true
  tasks:
    - name: Update apk and install required packages
      ansible.builtin.command:
        cmd: apk update && apk add nginx python3 py3-pip
      ignore_errors: yes

    - name: Install Flask with pip
      ansible.builtin.pip:
        name: Flask
        executable: /root/venv/bin/pip

    - name: Copy frontend index.html to nginx web root
      copy:
        src: /root/index.html
        dest: /var/lib/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'

    - name: Start nginx service
      ansible.builtin.command: nginx